# Generated by Django 3.2.9 on 2021-12-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'search_city_country',
            },
        ),
    ]
